from django.contrib.auth import get_user_model
from django.test import TestCase

from blog.models import Category, Comment, Post, Tag

User = get_user_model()


class PostModelTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.user = User.objects.create_user(username="author", password="pass12345")

    def test_slug_is_generated_from_title(self):
        post = Post.objects.create(title="Hello World", content="x", author=self.user)
        self.assertEqual(post.slug, "hello-world")

    def test_duplicate_titles_get_unique_slugs(self):
        first = Post.objects.create(title="Same Title", content="x", author=self.user)
        second = Post.objects.create(title="Same Title", content="x", author=self.user)
        self.assertEqual(first.slug, "same-title")
        self.assertEqual(second.slug, "same-title-2")

    def test_explicit_slug_is_preserved(self):
        post = Post.objects.create(
            title="A Title", slug="custom-slug", content="x", author=self.user
        )
        self.assertEqual(post.slug, "custom-slug")

    def test_default_status_is_published(self):
        post = Post.objects.create(title="T", content="x", author=self.user)
        self.assertEqual(post.status, Post.Status.PUBLISHED)

    def test_ordering_is_newest_first(self):
        older = Post.objects.create(title="Older", content="x", author=self.user)
        newer = Post.objects.create(title="Newer", content="x", author=self.user)
        self.assertEqual(list(Post.objects.all()), [newer, older])

    def test_excerpt_truncates_long_content(self):
        post = Post.objects.create(title="T", content="a" * 300, author=self.user)
        self.assertEqual(len(post.excerpt), 201)  # 200 chars + ellipsis
        self.assertTrue(post.excerpt.endswith("…"))

    def test_excerpt_keeps_short_content_intact(self):
        post = Post.objects.create(title="T", content="short", author=self.user)
        self.assertEqual(post.excerpt, "short")

    def test_likes_relationship(self):
        post = Post.objects.create(title="T", content="x", author=self.user)
        fan = User.objects.create_user(username="fan", password="pass12345")
        post.likes.add(fan)
        self.assertEqual(post.likes.count(), 1)
        self.assertIn(post, fan.liked_posts.all())


class CategoryTagModelTests(TestCase):
    def test_category_slug_autogenerated(self):
        category = Category.objects.create(name="Web Development")
        self.assertEqual(category.slug, "web-development")

    def test_tag_slug_autogenerated(self):
        tag = Tag.objects.create(name="REST API")
        self.assertEqual(tag.slug, "rest-api")

    def test_str_representations(self):
        self.assertEqual(str(Category.objects.create(name="Career")), "Career")
        self.assertEqual(str(Tag.objects.create(name="python")), "python")


class CommentModelTests(TestCase):
    def test_comments_ordered_oldest_first(self):
        user = User.objects.create_user(username="u", password="pass12345")
        post = Post.objects.create(title="T", content="x", author=user)
        first = Comment.objects.create(post=post, author=user, body="first")
        second = Comment.objects.create(post=post, author=user, body="second")
        self.assertEqual(list(post.comments.all()), [first, second])
